library(ggplot2)
#library(tidyverse)
install.packages("dplyr")
library(dplyr)

# The following code is for testing only
setwd("/Users/dzhang/DebinProjs/R/z_score")
test_data <- read.csv("test_data_wo_index_gender.csv", stringsAsFactors = TRUE)
test_data
mean(test_data$BMI)
sd(test_data$BMI)
zscore_data<-test_data %>% mutate(zscore=(BMI-mean(BMI))/sd(BMI))
zscore_data
write.csv(zscore_data, file="/Users/dzhang/DebinProjs/R/z_score/output/data_w_zscore.csv", row.names = FALSE)
u<-ggplot(data=zscore_data,aes(x=Gender, y=zscore))
u + geom_boxplot()

getZScore <- function(data, feature) {
  zscore_data<-data %>% mutate(zscore=({{feature}} - mean({{feature}}))/sd({{feature}}))
  zscore_data
}

getZScore(test_data,BMI)

# only select the rows with zscore<1.5 & zscore>-1.0
zscore_data[zscore_data$zscore<1.5 & zscore_data$zscore>-1.0, ]

# group by categorical variable
setwd("/Users/dzhang/DebinProjs/R/z_score")
test_data <- read.csv("test_data_wo_index_gender.csv", stringsAsFactors = TRUE)
test_data

# calculate counts for each group
test_data %>% group_by(Gender) %>% tally()
test_data %>% group_by(Gender) %>% mutate(zscore=(BMI-mean(BMI))/sd(BMI))


# only select certain columns
zscore_data<-test_data %>% mutate(zscore=(BMI-mean(BMI))/sd(BMI)) %>% select(Gender, BMI)
zscore_data

# The following code is for Evan's real data
setwd("/Users/dzhang/DebinProjs/R/z_score")
harmo_data <- read.csv("lh_combined_stats_07242022_1123pm_w_volume_filled.csv", stringsAsFactors = TRUE)
head(harmo_data)

# 1. superiorparietal.NumVert
zscore_superiorparietal.NumVert <- harmo_data %>% group_by(Dataset) %>% mutate(zscore=(superiorparietal.NumVert-mean(superiorparietal.NumVert))/sd(superiorparietal.NumVert)) %>% select(Dataset, superiorparietal.NumVert, zscore)
head(zscore_superiorparietal.NumVert)
write.csv(zscore_superiorparietal.NumVert, file="/Users/dzhang/DebinProjs/R/z_score/output/zscore_superiorparietal_NumVert.csv", row.names = FALSE)
u<-ggplot(data=zscore_superiorparietal.NumVert,aes(x=Dataset, y=zscore))
u + geom_boxplot()

# 2. caudalanteriorcingulate.SurfArea
zscore_caudalanteriorcingulate.SurfArea <- harmo_data %>% group_by(Dataset) %>% mutate(zscore=(caudalanteriorcingulate.SurfArea-mean(caudalanteriorcingulate.SurfArea))/sd(caudalanteriorcingulate.SurfArea)) %>% select(Dataset, caudalanteriorcingulate.SurfArea, zscore)
head(zscore_caudalanteriorcingulate.SurfArea)
write.csv(zscore_caudalanteriorcingulate.SurfArea, file="/Users/dzhang/DebinProjs/R/z_score/output/zscore_caudalanteriorcingulate.SurfArea.csv", row.names = FALSE)
u<-ggplot(data=zscore_caudalanteriorcingulate.SurfArea, aes(x=Dataset, y=zscore))
u + geom_boxplot()

# 3. cuneus.ThickStd
zscore_cuneus.ThickStd <- harmo_data %>% group_by(Dataset) %>% mutate(zscore=(cuneus.ThickStd-mean(cuneus.ThickStd))/sd(cuneus.ThickStd)) %>% select(Dataset, cuneus.ThickStd, zscore)
head(zscore_cuneus.ThickStd)
write.csv(zscore_caudalanteriorcingulate.SurfArea, file="/Users/dzhang/DebinProjs/R/z_score/output/zscore_cuneus.ThickStd.csv", row.names = FALSE)
u<-ggplot(data=zscore_cuneus.ThickStd, aes(x=Dataset, y=zscore))
u + geom_boxplot()

# 4. caudalmiddlefrontal.GrayVol
zscore_caudalmiddlefrontal.GrayVol <- harmo_data %>% group_by(Dataset) %>% mutate(zscore=(caudalmiddlefrontal.GrayVol-mean(caudalmiddlefrontal.GrayVol))/sd(caudalmiddlefrontal.GrayVol)) %>% select(Dataset, caudalmiddlefrontal.GrayVol, zscore)
head(zscore_caudalmiddlefrontal.GrayVol)
write.csv(zscore_caudalmiddlefrontal.GrayVol, file="/Users/dzhang/DebinProjs/R/z_score/output/zscore_caudalmiddlefrontal.GrayVol.csv", row.names = FALSE)
u<-ggplot(data=zscore_cuneus.ThickStd, aes(x=Dataset, y=zscore))
u + geom_boxplot()

# 5. plot all the features

# 5.a initialization step

library(ggplot2)
#library(tidyverse)
install.packages("dplyr")
library(dplyr)

getZScore <- function(data, feature) {
  zscore_data<-data %>% group_by(Dataset) %>% mutate(zscore=({{feature}} - mean({{feature}})) / sd({{feature}}))
  #head(zscore_data)
  u<-ggplot(data=zscore_data, aes(x=Dataset, y=zscore, fill=Dataset))
  u <- u + ylim(-2.5, 2.5)
  u + geom_boxplot()
}

getDiff <- function(data, feature, feature_name) {
  diff_data<-data %>% group_by(Dataset) %>% mutate(diff=({{feature}} - mean({{feature}})))
  #head(zscore_data)
  u<-ggplot(data=diff_data, aes(x=Dataset, y=diff, fill=Dataset))
  #u + geom_boxplot(alpha=0.5) + geom_jitter()
  u <- u + labs(title="Plot of diff from mean",
           x ="Dataset", y = paste("Diff for ", feature_name))
  #u <- u + ylim(-5,5)
  #u + geom_boxplot(aes(middle=mean(diff)), outlier.shape = NA)
  u + geom_boxplot(aes(middle=mean(diff)))
  #u + geom_boxplot() 
}


# 5.1.1 
setwd("/Users/dzhang/Gits/EvanBCHProj/harmonization_Evan_w_age_scannertype_wo_volume")
pre_data <- read.csv("lh_combined_stats_07242022_1123pm_w_volume_filled.csv")
#post_data <- read.csv("post_vol_in_covar.csv")
post_data <- read.csv("post_scannertype.csv")

getDiff(pre_data, Volume, "Volume")
getDiff(post_data, Harmo.Volume, "Volume")

getZScore(pre_data, Volume)
getZScore(post_data, Harmo.Volume)

getZScore(pre_data, middletemporal.GausCurv)
getZScore(post_data, middletemporal.GausCurv)
getZScore(pre_data, transversetemporal.ThickStd)
getZScore(post_data, transversetemporal.ThickStd)
getZScore(pre_data, transversetemporal.CurvInd)
getZScore(post_data, transversetemporal.CurvInd)
getZScore(pre_data, caudalmiddlefrontal.GausCurv)
getZScore(post_data, caudalmiddlefrontal.GausCurv)
getZScore(pre_data, fusiform.NumVert)
getZScore(post_data, fusiform.NumVert)
getZScore(pre_data, fusiform.MeanCurv)
getZScore(post_data, fusiform.MeanCurv)
getZScore(pre_data, superiortemporal.MeanCurv)
getZScore(post_data, superiortemporal.MeanCurv)
getZScore(pre_data, superiortemporal.GausCurv)
getZScore(post_data, superiortemporal.GausCurv)


getDiff(pre_data, superiorparietal.MeanCurv, "superiorparietal.MeanCurv")

getZScore(pre_data, superiorparietal.MeanCurv)
getZScore(post_data, superiorparietal.MeanCurv)

getDiff(pre_data, superiorparietal.FoldInd, "superiorparietal.FoldInd")
getDiff(post_data, superiorparietal.FoldInd, "superiorparietal.FoldInd")

getDiff(pre_data, caudalanteriorcingulate.GausCurv, "audalanteriorcingulate.GausCurv")
getDiff(post_data, caudalanteriorcingulate.GausCurv, "audalanteriorcingulate.GausCurv")

getDiff(pre_data, cuneus.ThickStd, "cuneus.ThickStd")
getDiff(post_data, cuneus.ThickStd, "cuneus.ThickStd")

getDiff(pre_data, temporalpole.ThickAvg, "temporalpole.ThickAvg")
getDiff(post_data, temporalpole.ThickAvg, "temporalpole.ThickAvg")

getDiff(pre_data, temporalpole.GausCurv, "emporalpole.GausCurv")
getDiff(post_data, temporalpole.GausCurv, "emporalpole.GausCurv")

getDiff(pre_data, temporalpole.CurvInd, "temporalpole.CurvInd")
getDiff(post_data, temporalpole.CurvInd, "temporalpole.CurvInd")

getDiff(pre_data, parahippocampal.GausCurv, "parahippocampal.GausCurv")
getDiff(post_data, parahippocampal.GausCurv, "parahippocampal.GausCurv")

getDiff(pre_data, rostralanteriorcingulate.GausCurv, "rostralanteriorcingulate.GausCurv")
getDiff(post_data, rostralanteriorcingulate.GausCurv, "rostralanteriorcingulate.GausCurv")


# 
setwd("/Users/dzhang/DebinProjs/R/z_score")

# 5.b For pre-harmonization data
harmo_data <- read.csv("lh_combined_stats_07242022_1123pm_w_volume_filled.csv", stringsAsFactors = TRUE)
head(harmo_data)

# 5.c For post-hormonization data
harmo_data <- read.csv("PostHarmon_all.csv", stringsAsFactors = TRUE)
head(harmo_data)

# 5.d plot boxplot for each feature
getZScore(harmo_data, caudalmiddlefrontal.MeanCurv)
getZScore(harmo_data, Volume)
getZScore(harmo_data, superiorparietal.NumVert)
getZScore(harmo_data, superiorparietal.SurfArea)
getZScore(harmo_data, superiorparietal.GrayVol)
getZScore(harmo_data, superiorparietal.ThickAvg)
getZScore(harmo_data, superiorparietal.ThickStd)
getZScore(harmo_data, superiorparietal.MeanCurv)
getZScore(harmo_data, superiorparietal.GausCurv)
getZScore(harmo_data, superiorparietal.FoldInd)
getZScore(harmo_data, superiorparietal.CurvInd)
getZScore(harmo_data, caudalanteriorcingulate.NumVert)
getZScore(harmo_data, caudalanteriorcingulate.SurfArea)
getZScore(harmo_data, caudalanteriorcingulate.GrayVol)
getZScore(harmo_data, caudalanteriorcingulate.ThickAvg)
getZScore(harmo_data, caudalanteriorcingulate.ThickStd)
getZScore(harmo_data, caudalanteriorcingulate.MeanCurv)
getZScore(harmo_data, caudalanteriorcingulate.GausCurv)
getZScore(harmo_data, caudalanteriorcingulate.FoldInd)
getZScore(harmo_data, caudalanteriorcingulate.CurvInd)
getZScore(harmo_data, cuneus.NumVert)
getZScore(harmo_data, cuneus.SurfArea)
getZScore(harmo_data, cuneus.GrayVol)
getZScore(harmo_data, cuneus.ThickAvg)
getZScore(harmo_data, cuneus.ThickStd)
getZScore(harmo_data, cuneus.MeanCurv)
getZScore(harmo_data, cuneus.GausCurv)
getZScore(harmo_data, cuneus.FoldInd)
getZScore(harmo_data, cuneus.CurvInd)
getZScore(harmo_data, temporalpole.NumVert)
getZScore(harmo_data, temporalpole.SurfArea)
getZScore(harmo_data, temporalpole.GrayVol)
getZScore(harmo_data, temporalpole.ThickAvg)
getZScore(harmo_data, temporalpole.ThickStd)
getZScore(harmo_data, temporalpole.MeanCurv)
getZScore(harmo_data, temporalpole.GausCurv)
getZScore(harmo_data, temporalpole.FoldInd)
getZScore(harmo_data, temporalpole.CurvInd)
getZScore(harmo_data, parahippocampal.NumVert)
getZScore(harmo_data, parahippocampal.SurfArea)
getZScore(harmo_data, parahippocampal.GrayVol)
getZScore(harmo_data, parahippocampal.ThickAvg)
getZScore(harmo_data, parahippocampal.ThickStd)
getZScore(harmo_data, parahippocampal.MeanCurv)
getZScore(harmo_data, parahippocampal.GausCurv)
getZScore(harmo_data, parahippocampal.FoldInd)
getZScore(harmo_data, parahippocampal.CurvInd)
getZScore(harmo_data, isthmuscingulate.NumVert)
getZScore(harmo_data, isthmuscingulate.SurfArea)
getZScore(harmo_data, isthmuscingulate.GrayVol)
getZScore(harmo_data, isthmuscingulate.ThickAvg)
getZScore(harmo_data, isthmuscingulate.ThickStd)
getZScore(harmo_data, isthmuscingulate.MeanCurv)
getZScore(harmo_data, isthmuscingulate.GausCurv)
getZScore(harmo_data, isthmuscingulate.FoldInd)
getZScore(harmo_data, isthmuscingulate.CurvInd)
getZScore(harmo_data, rostralanteriorcingulate.NumVert)
getZScore(harmo_data, rostralanteriorcingulate.SurfArea)
getZScore(harmo_data, rostralanteriorcingulate.GrayVol)
getZScore(harmo_data, rostralanteriorcingulate.ThickAvg)
getZScore(harmo_data, rostralanteriorcingulate.ThickStd)
getZScore(harmo_data, rostralanteriorcingulate.MeanCurv)
getZScore(harmo_data, rostralanteriorcingulate.GausCurv)
getZScore(harmo_data, rostralanteriorcingulate.FoldInd)
getZScore(harmo_data, rostralanteriorcingulate.CurvInd)
getZScore(harmo_data, middletemporal.NumVert)
getZScore(harmo_data, middletemporal.SurfArea)
getZScore(harmo_data, middletemporal.GrayVol)
getZScore(harmo_data, middletemporal.ThickAvg)
getZScore(harmo_data, middletemporal.ThickStd)
getZScore(harmo_data, middletemporal.MeanCurv)
getZScore(harmo_data, middletemporal.GausCurv)
getZScore(harmo_data, middletemporal.FoldInd)
getZScore(harmo_data, middletemporal.CurvInd)
getZScore(harmo_data, transversetemporal.NumVert)
getZScore(harmo_data, transversetemporal.SurfArea)
getZScore(harmo_data, transversetemporal.GrayVol)
getZScore(harmo_data, transversetemporal.ThickAvg)
getZScore(harmo_data, transversetemporal.ThickStd)
getZScore(harmo_data, transversetemporal.MeanCurv)
getZScore(harmo_data, transversetemporal.GausCurv)
getZScore(harmo_data, transversetemporal.FoldInd)
getZScore(harmo_data, transversetemporal.CurvInd)
getZScore(harmo_data, caudalmiddlefrontal.NumVert)
getZScore(harmo_data, caudalmiddlefrontal.SurfArea)
getZScore(harmo_data, caudalmiddlefrontal.GrayVol)
getZScore(harmo_data, caudalmiddlefrontal.ThickAvg)
getZScore(harmo_data, caudalmiddlefrontal.ThickStd)
getZScore(harmo_data, caudalmiddlefrontal.MeanCurv)
getZScore(harmo_data, caudalmiddlefrontal.GausCurv)
getZScore(harmo_data, caudalmiddlefrontal.FoldInd)
getZScore(harmo_data, caudalmiddlefrontal.CurvInd)
getZScore(harmo_data, fusiform.NumVert)
getZScore(harmo_data, fusiform.SurfArea)
getZScore(harmo_data, fusiform.GrayVol)
getZScore(harmo_data, fusiform.ThickAvg)
getZScore(harmo_data, fusiform.ThickStd)
getZScore(harmo_data, fusiform.MeanCurv)
getZScore(harmo_data, fusiform.GausCurv)
getZScore(harmo_data, fusiform.FoldInd)
getZScore(harmo_data, fusiform.CurvInd)
getZScore(harmo_data, parstriangularis.NumVert)
getZScore(harmo_data, parstriangularis.SurfArea)
getZScore(harmo_data, parstriangularis.GrayVol)
getZScore(harmo_data, parstriangularis.ThickAvg)
getZScore(harmo_data, parstriangularis.ThickStd)
getZScore(harmo_data, parstriangularis.MeanCurv)
getZScore(harmo_data, parstriangularis.GausCurv)
getZScore(harmo_data, parstriangularis.FoldInd)
getZScore(harmo_data, parstriangularis.CurvInd)
getZScore(harmo_data, entorhinal.NumVert)
getZScore(harmo_data, entorhinal.SurfArea)
getZScore(harmo_data, entorhinal.GrayVol)
getZScore(harmo_data, entorhinal.ThickAvg)
getZScore(harmo_data, entorhinal.ThickStd)
getZScore(harmo_data, entorhinal.MeanCurv)
getZScore(harmo_data, entorhinal.GausCurv)
getZScore(harmo_data, entorhinal.FoldInd)
getZScore(harmo_data, entorhinal.CurvInd)
getZScore(harmo_data, postcentral.NumVert)
getZScore(harmo_data, postcentral.SurfArea)
getZScore(harmo_data, postcentral.GrayVol)
getZScore(harmo_data, postcentral.ThickAvg)
getZScore(harmo_data, postcentral.ThickStd)
getZScore(harmo_data, postcentral.MeanCurv)
getZScore(harmo_data, postcentral.GausCurv)
getZScore(harmo_data, postcentral.FoldInd)
getZScore(harmo_data, postcentral.CurvInd)
getZScore(harmo_data, superiortemporal.NumVert)
getZScore(harmo_data, superiortemporal.SurfArea)
getZScore(harmo_data, superiortemporal.GrayVol)
getZScore(harmo_data, superiortemporal.ThickAvg)
getZScore(harmo_data, superiortemporal.ThickStd)
getZScore(harmo_data, superiortemporal.MeanCurv)
getZScore(harmo_data, superiortemporal.GausCurv)
getZScore(harmo_data, superiortemporal.FoldInd)
getZScore(harmo_data, superiortemporal.CurvInd)
getZScore(harmo_data, pericalcarine.NumVert)
getZScore(harmo_data, pericalcarine.SurfArea)
getZScore(harmo_data, pericalcarine.GrayVol)
getZScore(harmo_data, pericalcarine.ThickAvg)
getZScore(harmo_data, pericalcarine.ThickStd)
getZScore(harmo_data, pericalcarine.MeanCurv)
getZScore(harmo_data, pericalcarine.GausCurv)
getZScore(harmo_data, pericalcarine.FoldInd)
getZScore(harmo_data, pericalcarine.CurvInd)
getZScore(harmo_data, rostralmiddlefrontal.NumVert)
getZScore(harmo_data, rostralmiddlefrontal.SurfArea)
getZScore(harmo_data, rostralmiddlefrontal.GrayVol)
getZScore(harmo_data, rostralmiddlefrontal.ThickAvg)
getZScore(harmo_data, rostralmiddlefrontal.ThickStd)
getZScore(harmo_data, rostralmiddlefrontal.MeanCurv)
getZScore(harmo_data, rostralmiddlefrontal.GausCurv)
getZScore(harmo_data, rostralmiddlefrontal.FoldInd)
getZScore(harmo_data, rostralmiddlefrontal.CurvInd)
getZScore(harmo_data, parsorbitalis.NumVert)
getZScore(harmo_data, parsorbitalis.SurfArea)
getZScore(harmo_data, parsorbitalis.GrayVol)
getZScore(harmo_data, parsorbitalis.ThickAvg)
getZScore(harmo_data, parsorbitalis.ThickStd)
getZScore(harmo_data, parsorbitalis.MeanCurv)
getZScore(harmo_data, parsorbitalis.GausCurv)
getZScore(harmo_data, parsorbitalis.FoldInd)
getZScore(harmo_data, parsorbitalis.CurvInd)
getZScore(harmo_data, inferiortemporal.NumVert)
getZScore(harmo_data, inferiortemporal.SurfArea)
getZScore(harmo_data, inferiortemporal.GrayVol)
getZScore(harmo_data, inferiortemporal.ThickAvg)
getZScore(harmo_data, inferiortemporal.ThickStd)
getZScore(harmo_data, inferiortemporal.MeanCurv)
getZScore(harmo_data, inferiortemporal.GausCurv)
getZScore(harmo_data, inferiortemporal.FoldInd)
getZScore(harmo_data, inferiortemporal.CurvInd)
getZScore(harmo_data, frontalpole.NumVert)
getZScore(harmo_data, frontalpole.SurfArea)
getZScore(harmo_data, frontalpole.GrayVol)
getZScore(harmo_data, frontalpole.ThickAvg)
getZScore(harmo_data, frontalpole.ThickStd)
getZScore(harmo_data, frontalpole.MeanCurv)
getZScore(harmo_data, frontalpole.GausCurv)
getZScore(harmo_data, frontalpole.FoldInd)
getZScore(harmo_data, frontalpole.CurvInd)
getZScore(harmo_data, posteriorcingulate.NumVert)
getZScore(harmo_data, posteriorcingulate.SurfArea)
getZScore(harmo_data, posteriorcingulate.GrayVol)
getZScore(harmo_data, posteriorcingulate.ThickAvg)
getZScore(harmo_data, posteriorcingulate.ThickStd)
getZScore(harmo_data, posteriorcingulate.MeanCurv)
getZScore(harmo_data, posteriorcingulate.GausCurv)
getZScore(harmo_data, posteriorcingulate.FoldInd)
getZScore(harmo_data, posteriorcingulate.CurvInd)
getZScore(harmo_data, medialorbitofrontal.NumVert)
getZScore(harmo_data, medialorbitofrontal.SurfArea)
getZScore(harmo_data, medialorbitofrontal.GrayVol)
getZScore(harmo_data, medialorbitofrontal.ThickAvg)
getZScore(harmo_data, medialorbitofrontal.ThickStd)
getZScore(harmo_data, medialorbitofrontal.MeanCurv)
getZScore(harmo_data, medialorbitofrontal.GausCurv)
getZScore(harmo_data, medialorbitofrontal.FoldInd)
getZScore(harmo_data, medialorbitofrontal.CurvInd)
getZScore(harmo_data, lateraloccipital.NumVert)
getZScore(harmo_data, lateraloccipital.SurfArea)
getZScore(harmo_data, lateraloccipital.GrayVol)
getZScore(harmo_data, lateraloccipital.ThickAvg)
getZScore(harmo_data, lateraloccipital.ThickStd)
getZScore(harmo_data, lateraloccipital.MeanCurv)
getZScore(harmo_data, lateraloccipital.GausCurv)
getZScore(harmo_data, lateraloccipital.FoldInd)
getZScore(harmo_data, lateraloccipital.CurvInd)
getZScore(harmo_data, bankssts.NumVert)
getZScore(harmo_data, bankssts.SurfArea)
getZScore(harmo_data, bankssts.GrayVol)
getZScore(harmo_data, bankssts.ThickAvg)
getZScore(harmo_data, bankssts.ThickStd)
getZScore(harmo_data, bankssts.MeanCurv)
getZScore(harmo_data, bankssts.GausCurv)
getZScore(harmo_data, bankssts.FoldInd)
getZScore(harmo_data, bankssts.CurvInd)
getZScore(harmo_data, paracentral.NumVert)
getZScore(harmo_data, paracentral.SurfArea)
getZScore(harmo_data, paracentral.GrayVol)
getZScore(harmo_data, paracentral.ThickAvg)
getZScore(harmo_data, paracentral.ThickStd)
getZScore(harmo_data, paracentral.MeanCurv)
getZScore(harmo_data, paracentral.GausCurv)
getZScore(harmo_data, paracentral.FoldInd)
getZScore(harmo_data, paracentral.CurvInd)
getZScore(harmo_data, insula.NumVert)
getZScore(harmo_data, insula.SurfArea)
getZScore(harmo_data, insula.GrayVol)
getZScore(harmo_data, insula.ThickAvg)
getZScore(harmo_data, insula.ThickStd)
getZScore(harmo_data, insula.MeanCurv)
getZScore(harmo_data, insula.GausCurv)
getZScore(harmo_data, insula.FoldInd)
getZScore(harmo_data, insula.CurvInd)
getZScore(harmo_data, supramarginal.NumVert)
getZScore(harmo_data, supramarginal.SurfArea)
getZScore(harmo_data, supramarginal.GrayVol)
getZScore(harmo_data, supramarginal.ThickAvg)
getZScore(harmo_data, supramarginal.ThickStd)
getZScore(harmo_data, supramarginal.MeanCurv)
getZScore(harmo_data, supramarginal.GausCurv)
getZScore(harmo_data, supramarginal.FoldInd)
getZScore(harmo_data, supramarginal.CurvInd)
getZScore(harmo_data, lingual.NumVert)
getZScore(harmo_data, lingual.SurfArea)
getZScore(harmo_data, lingual.GrayVol)
getZScore(harmo_data, lingual.ThickAvg)
getZScore(harmo_data, lingual.ThickStd)
getZScore(harmo_data, lingual.MeanCurv)
getZScore(harmo_data, lingual.GausCurv)
getZScore(harmo_data, lingual.FoldInd)
getZScore(harmo_data, lingual.CurvInd)
getZScore(harmo_data, parsopercularis.NumVert)
getZScore(harmo_data, parsopercularis.SurfArea)
getZScore(harmo_data, parsopercularis.GrayVol)
getZScore(harmo_data, parsopercularis.ThickAvg)
getZScore(harmo_data, parsopercularis.ThickStd)
getZScore(harmo_data, parsopercularis.MeanCurv)
getZScore(harmo_data, parsopercularis.GausCurv)
getZScore(harmo_data, parsopercularis.FoldInd)
getZScore(harmo_data, parsopercularis.CurvInd)
getZScore(harmo_data, inferiorparietal.NumVert)
getZScore(harmo_data, inferiorparietal.SurfArea)
getZScore(harmo_data, inferiorparietal.GrayVol)
getZScore(harmo_data, inferiorparietal.ThickAvg)
getZScore(harmo_data, inferiorparietal.ThickStd)
getZScore(harmo_data, inferiorparietal.MeanCurv)
getZScore(harmo_data, inferiorparietal.GausCurv)
getZScore(harmo_data, inferiorparietal.FoldInd)
getZScore(harmo_data, inferiorparietal.CurvInd)
getZScore(harmo_data, precentral.NumVert)
getZScore(harmo_data, precentral.SurfArea)
getZScore(harmo_data, precentral.GrayVol)
getZScore(harmo_data, precentral.ThickAvg)
getZScore(harmo_data, precentral.ThickStd)
getZScore(harmo_data, precentral.MeanCurv)
getZScore(harmo_data, precentral.GausCurv)
getZScore(harmo_data, precentral.FoldInd)
getZScore(harmo_data, precentral.CurvInd)
getZScore(harmo_data, superiorfrontal.NumVert)
getZScore(harmo_data, superiorfrontal.SurfArea)
getZScore(harmo_data, superiorfrontal.GrayVol)
getZScore(harmo_data, superiorfrontal.ThickAvg)
getZScore(harmo_data, superiorfrontal.ThickStd)
getZScore(harmo_data, superiorfrontal.MeanCurv)
getZScore(harmo_data, superiorfrontal.GausCurv)
getZScore(harmo_data, superiorfrontal.FoldInd)
getZScore(harmo_data, superiorfrontal.CurvInd)
getZScore(harmo_data, lateralorbitofrontal.NumVert)
getZScore(harmo_data, lateralorbitofrontal.SurfArea)
getZScore(harmo_data, lateralorbitofrontal.GrayVol)
getZScore(harmo_data, lateralorbitofrontal.ThickAvg)
getZScore(harmo_data, lateralorbitofrontal.ThickStd)
getZScore(harmo_data, lateralorbitofrontal.MeanCurv)
getZScore(harmo_data, lateralorbitofrontal.GausCurv)
getZScore(harmo_data, lateralorbitofrontal.FoldInd)
getZScore(harmo_data, lateralorbitofrontal.CurvInd)
getZScore(harmo_data, precuneus.NumVert)
getZScore(harmo_data, precuneus.SurfArea)
getZScore(harmo_data, precuneus.GrayVol)
getZScore(harmo_data, precuneus.ThickAvg)
getZScore(harmo_data, precuneus.ThickStd)
getZScore(harmo_data, precuneus.MeanCurv)
getZScore(harmo_data, precuneus.GausCurv)
getZScore(harmo_data, precuneus.FoldInd)
getZScore(harmo_data, precuneus.CurvInd)

# 6. features that have relatively big zscore deviation
getZScore(pre_data, superiorparietal.MeanCurv)
getZScore(post_data, superiorparietal.MeanCurv)

getZScore(pre_data, superiorparietal.FoldInd)
getZScore(post_data, superiorparietal.FoldInd)

getZScore(pre_data, caudalanteriorcingulate.GausCurv)
getZScore(post_data, caudalanteriorcingulate.GausCurv)
getZScore(harmo_data, cuneus.ThickStd)
getZScore(harmo_data, temporalpole.ThickAvg)
getZScore(harmo_data, temporalpole.GausCurv)
getZScore(harmo_data, temporalpole.CurvInd)
getZScore(harmo_data, parahippocampal.GausCurv)
getZScore(harmo_data, rostralanteriorcingulate.GausCurv)
getZScore(harmo_data, middletemporal.GausCurv)
getZScore(harmo_data, transversetemporal.ThickStd)
getZScore(harmo_data, transversetemporal.CurvInd)
getZScore(harmo_data, caudalmiddlefrontal.GausCurv)
getZScore(harmo_data, fusiform.NumVert)
getZScore(harmo_data, fusiform.MeanCurv)
getZScore(harmo_data, superiortemporal.MeanCurv)
getZScore(harmo_data, superiortemporal.GausCurv)
getZScore(harmo_data, inferiortemporal.GausCurv)
getZScore(harmo_data, inferiorparietal.GausCurv)
getZScore(harmo_data, superiorfrontal.GausCurv)
